name: Build and test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Compile
        # Exclude Day12 as it uses gson library
        run: find src -name \*.java | xargs javac -d out

      - name: Run tests
        run: java -cp out advent2015.Main test
